# scons script for NiL isn't Liero (utils/cpio-maker)
# See www.scons.org for details

#
# This file is part of NiL.
# Copyright (C) 2004 Christoph Brill <egore@users.sourceforge.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#print "building cpio maker"

env = Environment()
env.Append(CPPPATH = '../../src')
env.Append(CPPFLAGS = '-DWITHOUT_SDL -DUSE_LIBBZIP2')
env.SourceSignatures('MD5')
env.Program(target = 'cpio-maker', LIBS = ['z', 'bz2', 'pthread'], source = Split('make-cpio.cpp ../../src/common/vfs/loader.cpp ../../src/common/console/console.cpp ../../src/common/console/logmsg.cpp ../../src/common/exception.cpp ../../src/common/vfs/loader_source_directory.cpp ../../src/common/vfs/loader_source_cpio.cpp ../../src/common/vfs/vfs_decompress_gzip.cpp ../../src/common/vfs/vfs_decompress_bzip2.cpp ../../src/common/vfs/vfs_pathexpander.cpp ../../src/common/vfs/vfs_mapped_arena.cpp ../../src/common/vfs/vfs_memory_arena.cpp ../../src/common/vfs/vfs_anonymous_arena.cpp ../../src/common/vfs/vfs_decompress.cpp ../../src/common/vfs/vfs_subdivided_arena.cpp ../../src/common/vfs/vfs_fixed_arena.cpp ../../src/common/vfs/vfs_file_table.cpp ../../src/common/vfs/vfs_inplace_alterable.cpp ../../src/common/misc.cpp'))
